### PR TITLE
Remove app from app catalogs

### PR DESCRIPTION
**Pull request by glitchcrab**
Stop CI working and add a note to the readme.

### CODE REVIEW

**Review by yasn77 — CHANGES_REQUESTED** [review]
@glitchcrab Rather than breaking CI. Would it just be better to remove `.cicleci/config.yaml` file?

I am not a big fan of leaving things in a broken state.

**Comment by glitchcrab** [comment]
> @glitchcrab Rather than breaking CI. Would it just be better to remove `.cicleci/config.yaml` file?
> 
> I am not a big fan of leaving things in a broken state.

can do, I was thinking we'd be removing the CI job too but maybe that should stay in case we pick this up again in the future.

**Comment by yasn77** [comment]
> > @glitchcrab Rather than breaking CI. Would it just be better to remove `.cicleci/config.yaml` file?
> > I am not a big fan of leaving things in a broken state.
> 
> can do, I was thinking we'd be removing the CI job too but maybe that should stay in case we pick this up again in the future.

Yeh... We can decide what to do with CI later. Just don't like seeing red things :smile_cat:

**Comment by yasn77** [comment]
> > > @glitchcrab Rather than breaking CI. Would it just be better to remove `.cicleci/config.yaml` file?
> > > I am not a big fan of leaving things in a broken state.
> > 
> > 
> > can do, I was thinking we'd be removing the CI job too but maybe that should stay in case we pick this up again in the future.
> 
> Yeh... We can decide what to do with CI later. Just don't like seeing red things

Seems like CI still failed, so will need to delete the job after all

**Review by yasn77 — APPROVED** [review]
CI job should also be removed.

**Comment by glitchcrab** [comment]
> CI job should also be removed.

yeah it's still polling this repo for changes. I've left the build job intact but disabled it from building. this way we keep the history but stop the failing builds.

**Pull request merged**
